include_guard(GLOBAL)

function(handle_compiler_flags)
    cmake_parse_arguments(ARG "" "CXX_STANDARD" "" ${ARGN})

    if(NOT ARG_CXX_STANDARD)
        set(ARG_CXX_STANDARD 20)
    endif()

    # Host-native CPU flags are not portable across toolchains; target flags must be explicit.
    if(CMAKE_CROSSCOMPILING AND CPU_ENABLE_NATIVE_TUNING)
        message(STATUS "Disabling CPU_ENABLE_NATIVE_TUNING for cross-compiling. Use CPU_EXTRA_OPT_FLAGS for target-specific CPU flags.")
        set(CPU_ENABLE_NATIVE_TUNING OFF CACHE BOOL "Enable -march=native -mtune=native for GNU/Clang in optimized builds" FORCE)
        set(CPU_ENABLE_NATIVE_TUNING OFF PARENT_SCOPE)
    endif()

    if(CMAKE_CROSSCOMPILING AND CPU_ENABLE_SIMD)
        string(TOLOWER "${CPU_SIMD_LEVEL}" _cross_cpu_simd_level)
        if(_cross_cpu_simd_level STREQUAL "native")
            message(FATAL_ERROR "CPU_SIMD_LEVEL=native is not valid while cross-compiling. Set CPU_ENABLE_SIMD=OFF or pass target-specific flags through CPU_EXTRA_OPT_FLAGS.")
        endif()
    endif()

    set(CMAKE_CXX_STANDARD ${ARG_CXX_STANDARD} PARENT_SCOPE)
    set(CMAKE_CXX_STANDARD_REQUIRED ON PARENT_SCOPE)
    set(CMAKE_CXX_EXTENSIONS OFF PARENT_SCOPE)

    set(_initial_c_flags "${CMAKE_C_FLAGS}")
    set(_initial_cxx_flags "${CMAKE_CXX_FLAGS}")

    set(_common_c_warnings -Wall -Wextra)
    set(_common_cxx_warnings ${_common_c_warnings} -Wsuggest-override)
    set(_debug_flags -Og -g -fmax-errors=3)
    set(_debug_sanitizers)
    if(SANITIZE_BUILD AND SANITIZERS)
        set(_debug_sanitizers -fsanitize=${SANITIZERS})
    endif()

    set(_release_flags -O3 -DNDEBUG -fmax-errors=1)
    set(_relwithdebinfo_flags -O2 -g -DNDEBUG)
    set(_noptim_flags -O0 -g3 -fno-omit-frame-pointer -fno-inline -fno-optimize-sibling-calls)
    set(_safety_warnings -Wnull-dereference -Wfloat-equal -fdelete-null-pointer-checks -Wconversion)

    set(_cpu_opt_flags)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        if(CPU_ENABLE_NATIVE_TUNING)
            list(APPEND _cpu_opt_flags -march=native -mtune=native)
        endif()

        if(CPU_ENABLE_FMA)
            list(APPEND _cpu_opt_flags -mfma)
        endif()

        if(CPU_ENABLE_SIMD)
            string(TOLOWER "${CPU_SIMD_LEVEL}" _cpu_simd_level)
            if(_cpu_simd_level STREQUAL "native")
                list(APPEND _cpu_opt_flags -march=native -mtune=native)
            elseif(_cpu_simd_level STREQUAL "sse4.2" OR _cpu_simd_level STREQUAL "sse4_2")
                list(APPEND _cpu_opt_flags -msse4.2)
            elseif(_cpu_simd_level STREQUAL "avx")
                list(APPEND _cpu_opt_flags -mavx)
            elseif(_cpu_simd_level STREQUAL "avx2")
                list(APPEND _cpu_opt_flags -mavx2)
            elseif(_cpu_simd_level STREQUAL "avx512f")
                list(APPEND _cpu_opt_flags -mavx512f)
            else()
                message(FATAL_ERROR "Unsupported CPU_SIMD_LEVEL='${CPU_SIMD_LEVEL}'. Supported values: native,sse4.2,avx,avx2,avx512f")
            endif()
        endif()

        if(DEFINED CPU_EXTRA_OPT_FLAGS AND NOT "${CPU_EXTRA_OPT_FLAGS}" STREQUAL "")
            separate_arguments(_cpu_extra_opt_flags UNIX_COMMAND "${CPU_EXTRA_OPT_FLAGS}")
            list(APPEND _cpu_opt_flags ${_cpu_extra_opt_flags})
        endif()

        list(REMOVE_DUPLICATES _cpu_opt_flags)
    elseif(CPU_ENABLE_NATIVE_TUNING OR CPU_ENABLE_FMA OR CPU_ENABLE_SIMD OR (DEFINED CPU_EXTRA_OPT_FLAGS AND NOT "${CPU_EXTRA_OPT_FLAGS}" STREQUAL ""))
        message(WARNING "CPU optimization toggles are intended for GNU/Clang compilers. Current compiler is '${CMAKE_CXX_COMPILER_ID}'.")
    endif()

    set(_debug_c_flags ${_debug_flags} ${_common_c_warnings} ${_debug_sanitizers})
    set(_debug_cxx_flags ${_debug_flags} ${_common_cxx_warnings} ${_debug_sanitizers})
    set(_release_c_flags ${_release_flags} ${_common_c_warnings})
    set(_release_cxx_flags ${_release_flags} ${_common_cxx_warnings})
    set(_relwithdebinfo_c_flags ${_relwithdebinfo_flags} ${_common_c_warnings} ${_safety_warnings})
    set(_relwithdebinfo_cxx_flags ${_relwithdebinfo_flags} ${_common_cxx_warnings} ${_safety_warnings} -Wnon-virtual-dtor)
    set(_noptim_c_flags ${_noptim_flags} ${_common_c_warnings} ${_safety_warnings})
    set(_noptim_cxx_flags ${_noptim_flags} ${_common_cxx_warnings} ${_safety_warnings} -Wnon-virtual-dtor)

    list(APPEND _release_c_flags ${_cpu_opt_flags})
    list(APPEND _release_cxx_flags ${_cpu_opt_flags})
    list(APPEND _relwithdebinfo_c_flags ${_cpu_opt_flags})
    list(APPEND _relwithdebinfo_cxx_flags ${_cpu_opt_flags})

    set(_user_c_flags)
    if(NOT "${_initial_c_flags}" STREQUAL "")
        separate_arguments(_initial_c_flags_list UNIX_COMMAND "${_initial_c_flags}")
        list(APPEND _user_c_flags ${_initial_c_flags_list})
    endif()
    if(DEFINED EXTRA_C_FLAGS AND NOT "${EXTRA_C_FLAGS}" STREQUAL "")
        separate_arguments(_extra_c_flags_list UNIX_COMMAND "${EXTRA_C_FLAGS}")
        list(APPEND _user_c_flags ${_extra_c_flags_list})
    endif()
    list(REMOVE_DUPLICATES _user_c_flags)

    set(_user_cxx_flags)
    if(NOT "${_initial_cxx_flags}" STREQUAL "")
        separate_arguments(_initial_cxx_flags_list UNIX_COMMAND "${_initial_cxx_flags}")
        list(APPEND _user_cxx_flags ${_initial_cxx_flags_list})
    endif()
    if(DEFINED EXTRA_CXX_FLAGS AND NOT "${EXTRA_CXX_FLAGS}" STREQUAL "")
        separate_arguments(_extra_cxx_flags_list UNIX_COMMAND "${EXTRA_CXX_FLAGS}")
        list(APPEND _user_cxx_flags ${_extra_cxx_flags_list})
    endif()
    list(REMOVE_DUPLICATES _user_cxx_flags)

    list(APPEND _debug_c_flags ${_user_c_flags})
    list(APPEND _release_c_flags ${_user_c_flags})
    list(APPEND _relwithdebinfo_c_flags ${_user_c_flags})
    list(APPEND _noptim_c_flags ${_user_c_flags})
    list(APPEND _debug_cxx_flags ${_user_cxx_flags})
    list(APPEND _release_cxx_flags ${_user_cxx_flags})
    list(APPEND _relwithdebinfo_cxx_flags ${_user_cxx_flags})
    list(APPEND _noptim_cxx_flags ${_user_cxx_flags})

    string(JOIN " " _c_flags_debug ${_debug_c_flags})
    string(JOIN " " _cxx_flags_debug ${_debug_cxx_flags})
    string(JOIN " " _c_flags_release ${_release_c_flags})
    string(JOIN " " _cxx_flags_release ${_release_cxx_flags})
    string(JOIN " " _c_flags_relwithdebinfo ${_relwithdebinfo_c_flags})
    string(JOIN " " _cxx_flags_relwithdebinfo ${_relwithdebinfo_cxx_flags})
    string(JOIN " " _c_flags_noptim ${_noptim_c_flags})
    string(JOIN " " _cxx_flags_noptim ${_noptim_cxx_flags})

    set(CMAKE_C_FLAGS_DEBUG "${_c_flags_debug}" PARENT_SCOPE)
    set(CMAKE_CXX_FLAGS_DEBUG "${_cxx_flags_debug}" PARENT_SCOPE)
    set(CMAKE_C_FLAGS_RELEASE "${_c_flags_release}" PARENT_SCOPE)
    set(CMAKE_CXX_FLAGS_RELEASE "${_cxx_flags_release}" PARENT_SCOPE)
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "${_c_flags_relwithdebinfo}" PARENT_SCOPE)
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${_cxx_flags_relwithdebinfo}" PARENT_SCOPE)
    set(CMAKE_C_FLAGS_NOPTIM "${_c_flags_noptim}" PARENT_SCOPE)
    set(CMAKE_CXX_FLAGS_NOPTIM "${_cxx_flags_noptim}" PARENT_SCOPE)

    if(NO_OPTIMIZATION)
        set(CMAKE_C_FLAGS_DEBUG "${_c_flags_noptim}" PARENT_SCOPE)
        set(CMAKE_CXX_FLAGS_DEBUG "${_cxx_flags_noptim}" PARENT_SCOPE)
        set(CMAKE_C_FLAGS_RELEASE "${_c_flags_noptim}" PARENT_SCOPE)
        set(CMAKE_CXX_FLAGS_RELEASE "${_cxx_flags_noptim}" PARENT_SCOPE)
        set(CMAKE_C_FLAGS_RELWITHDEBINFO "${_c_flags_noptim}" PARENT_SCOPE)
        set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${_cxx_flags_noptim}" PARENT_SCOPE)
        set(CMAKE_C_FLAGS_MINSIZEREL "${_c_flags_noptim}" PARENT_SCOPE)
        set(CMAKE_CXX_FLAGS_MINSIZEREL "${_cxx_flags_noptim}" PARENT_SCOPE)
    endif()
endfunction()

function(handle_compiler_flags_interface)
    cmake_parse_arguments(ARG "" "TARGET" "" ${ARGN})
    if(NOT ARG_TARGET)
        message(FATAL_ERROR "handle_compiler_flags_interface requires TARGET")
    endif()
    if(NOT TARGET ${ARG_TARGET})
        message(FATAL_ERROR "handle_compiler_flags_interface TARGET does not exist: ${ARG_TARGET}")
    endif()

    target_compile_features(${ARG_TARGET} INTERFACE cxx_std_20)

    if(NO_OPTIMIZATION)
        message(STATUS "NO_OPTIMIZATION keeps assertions enabled and emits profiler-friendly debug flags.")
    elseif(CMAKE_BUILD_TYPE_LOWER MATCHES "debug")
        set(_sanitizer_flags)
        if(SANITIZE_BUILD AND SANITIZERS)
            set(_sanitizer_flags -fsanitize=${SANITIZERS})
        endif()
        target_compile_options(${ARG_TARGET} INTERFACE
            ${_sanitizer_flags}
            -fno-omit-frame-pointer
        )
        target_link_options(${ARG_TARGET} INTERFACE
            ${_sanitizer_flags}
            -fno-omit-frame-pointer
        )
    elseif(NOT (CMAKE_BUILD_TYPE_LOWER MATCHES "release" OR CMAKE_BUILD_TYPE_LOWER MATCHES "relwithdebinfo"))
        message(FATAL_ERROR "Unknown build type: ${CMAKE_BUILD_TYPE}. Stopping build.")
    endif()
endfunction()

function(print_compiler_flags_summary)
    if(MSVC OR XCODE_VERSION)
        return()
    endif()

    message(STATUS "Build type                                : ${CMAKE_BUILD_TYPE}")
    message(STATUS "Optimization override:                    : ${NO_OPTIMIZATION}")

    set(_display_c_flags "${CMAKE_C_FLAGS}")
    set(_display_cxx_flags "${CMAKE_CXX_FLAGS}")
    if(NO_OPTIMIZATION)
        set(_display_c_flags "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_NOPTIM}")
        set(_display_cxx_flags "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_NOPTIM}")
    elseif(CMAKE_BUILD_TYPE_LOWER MATCHES "debug")
        set(_display_c_flags "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_DEBUG}")
        set(_display_cxx_flags "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}")
    elseif(CMAKE_BUILD_TYPE_LOWER MATCHES "release" AND NOT NO_OPTIMIZATION)
        set(_display_c_flags "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_RELEASE}")
        set(_display_cxx_flags "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE}")
    elseif(CMAKE_BUILD_TYPE_LOWER MATCHES "relwithdebinfo" AND NOT NO_OPTIMIZATION)
        set(_display_c_flags "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_RELWITHDEBINFO}")
        set(_display_cxx_flags "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
    endif()

    string(STRIP "${_display_c_flags}" _display_c_flags)
    string(STRIP "${_display_cxx_flags}" _display_cxx_flags)
    message(STATUS "  C compilation flags                     : ${_display_c_flags}")
    message(STATUS "  C++ compilation flags                   : ${_display_cxx_flags}")
endfunction()
